= How to contribute to the AcMeta and SONAR-netCDF4 documents
Erin LaBrecque
:revnumber: 0.01
:revdate: 2020-02-25
:imagesdir: images\
:toc: preamble
:toclevels: 4
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


Welcome!

If you are comfortable with Git and GitHub, head over to the link:experienced_github_users.adoc[A quick workflow for experienced Git, GitHub, and Asciidoc users] document. The rest of you, please keep reading.


== Where do I start?
=== Here
.Help
If you still have questions about _how_ to contribute to the convention documents after reading through the files in the "How to contribute" directory (folder), please submit your question in an https://github.com/ices-eg/wg_WGFAST/issues[issue] in the `ices-eg/wg_WGFAST` repository and mention `@erinann`. +
{empty} +

.Contribute to the help documents
These help files are a work in progress. Comments and suggestions are welcomed and encouraged! Please submit an https://github.com/ices-eg/wg_WGFAST/issues[issue] with your comments in the `ices-eg/wg_WGFAST` repository and mention `@erinann`.

=== What's next?
1. Read the rest of this page. This is a README file. It is like a homepage for GitHub repositories and directories within repositories.
2. Read through the link:1_suggested_setup.adoc[Suggested setup to contribute to the ICES WGFAST convention documents].
2. Read through the link:2_suggested_workflow.adoc[Suggested workflow to contribute to the ICES WGFAST convention documents].
3. Read the individual help files when needed.

[NOTE]
====
As of this writing, there are three directories within the wg_WGFAST repository. +

* `How_to_contribute` directory - Help files on how to contribute to the convention documents. You are in this directory if you are reading this.
* `AcMeta` directory - Holds the _A metadata convention for processed acoustic data from active acoustic systems_ document and supporting files.
* `SONAR-netCDR` directory - Holds the _The SONAR-netCDF4 convention for sonar data, Version 1.1_ in the `docs` subdirectory.
====

Links to all the help files are at the bottom of this document.

== Git and GitHub
If do not know what Git commits are, or if you think "forking a repository" refers to dueling with cutlery, please read through the Git and GitHub help files before attempting to contribute. We will not make you a Git or GitHub expert, but we will get you sorted enough to know how to stage commits, write useful commit messages, push those commits to your remote repository, pull updates from an upstream repository, and submit pull requests in order to contribute to the convention documents.

== AsciiDoc markup
If you do not know what markup language is (specifically AsciiDoc markup) or how to preview markup documents, please read though the Text Editors/IDEs and AsciiDoc help files. Again, we will not make you an expert in these things, but we will get you editing with as little pain as possible.

CAUTION: Previewing AsciiDoc markup documents will require you to install browser extensions and view the documents in your web browser. Creating backends (HTML, PDF, DocBook, etc.) on your local machine will require you to install Ruby, Ruby Version Manager, and the Asciidoctor toolchain. These installations can get complicated if you are not deeply familiar with your operating system.

In lieu of installing browser extensions, the Asciidoctor toolchain, and all the dependencies, we recommend using a text editor/IDE that can edit and provide live previews of AsciiDoc documents. *AsciidocFX*, *Atom*, or *Brackets* are three suggested text editors/IDEs.

== AsciidocFX, Atom, Brackets text editors/IDEs
AsciidocFX, Atom, and Brackets are text editors/IDEs that can read, edit, and live preview AsciiDoc documents. All three editors can interact with GitHub through a terminal or a terminal emulator or a GUI.

WARNING: Previews of citations in AsciiDoc documents do not currently work in Atom or Brackets. Previews of math equation (LaTex math) in AsciiDoc documents does not currently work in Atom, but you can change the settings of the AsciiDoc preview pane in Brackets to preview math equations. +


== Links To Help Files
- link:1_suggested_setup.adoc[Suggested setup to contribute to the ICES WGFAST convention documents] +
- link:2_suggested_workflow.adoc[Suggested workflow to contribute to the ICES WGFAST convention documents] +
- link:3_github_help.adoc[GitHub help] +
- link:4_git_help.adoc[Git help]  +
- link:5_plain_text_editor_help.adoc[Text editors/IDEs help]  +
- link:6_asciidoc_help.adoc[AsciiDoc help]  +
- link:experienced_github_users.adoc[A quick workflow for experienced Git, GitHub, and Asciidoc users] +
{empty} +

NOTE: The help files are written in AsciiDoc (.adoc) markup. If you want to take a quick peek, click on the `Raw` button.

{empty} +


.File name -> Document name
1_suggested_setup.adoc -> Suggested setup to contribute to the ICES WGFAST convention documents +
2_suggested_workflow.adoc -> Suggested workflow to contribute to the ICES WGFAST convention documents +
3_github_help.adoc -> GitHub help +
4_git_help.adoc -> Git help +
5_plain_text_editor_help.adoc -> Text editors/IDEs help +
6_asciidoc_help.adoc -> AsciiDoc help +
experienced_github_users.adoc -> A quick workflow for experienced Git, GitHub, and Asciidoc users +
README.adoc -> How to contribute to the AcMeta and SONAR-netCDF4 documents +
